
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rastko
 */
public class Calculator extends java.awt.Frame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fldNumTwo = new javax.swing.JTextField();
        fldResult = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        fldNumOne = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculator", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Number 1:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 30));
        jLabel1.getAccessibleContext().setAccessibleName("lblNumOne");

        jLabel2.setText("Number 2:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 60, 30));
        jLabel2.getAccessibleContext().setAccessibleName("lblNumTwo");

        jLabel3.setText("Result:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 50, -1));
        jLabel3.getAccessibleContext().setAccessibleName("lblResult");

        jPanel1.add(fldNumTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 60, -1));
        fldNumTwo.getAccessibleContext().setAccessibleName("fldNumTwo");

        jPanel1.add(fldResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 60, 20));
        fldResult.getAccessibleContext().setAccessibleName("fldResult");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 60, -1));
        btnAdd.getAccessibleContext().setAccessibleName("btnAdd");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));
        btnReset.getAccessibleContext().setAccessibleName("btnReset");

        jPanel1.add(fldNumOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        fldNumOne.setText("");  //"brisanje" polja za ponovni unos brojeva
        fldNumTwo.setText("");
        fldResult.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        Thread s = new Thread(new Server());    //objekat klase Thread
        s.start();  //startovanje niti koja je zapravo Server koji ceka poruku klijenta

        try (Socket cn = new Socket("localhost", 100);  //ARM klijentske strane
                BufferedReader in = new BufferedReader(new InputStreamReader(cn.getInputStream()));
                BufferedOutputStream out = new BufferedOutputStream(cn.getOutputStream());) {

            String a = fldNumOne.getText() + "+" + fldNumTwo.getText(); //promenljiva definisana ocitavanjem unetih vrednosti iz
                                                                        //odgovarajucih text field-ova

            out.write(a.getBytes());    //slanje poruke serveru
            out.write("\n".getBytes());
            out.flush();    //ciscenje, zatvaranje poruke

            String total = in.readLine();   //citanje poruke pristigle od servera
            fldResult.setText(total);   //ispis poruke u odgovarajucem text field-u


        } catch (IOException exception) {

            System.out.println(exception.getMessage());

        }

    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField fldNumOne;
    private javax.swing.JTextField fldNumTwo;
    private javax.swing.JTextField fldResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
